"$schema" = "./node_modules/wrangler/config-schema.json"
main = "custom-worker.ts"
name = "zenshi"
compatibility_date = "2026-02-04"
compatibility_flags = [ "nodejs_compat" ]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[vars]
AUTH_URL = "https://zenshi.dev"
AUTH_TRUST_HOST = "true"
NEXT_PUBLIC_SITE_URL = "https://zenshi.dev"

[[routes]]
pattern = "zenshi.dev"
custom_domain = true

[[d1_databases]]
binding = "DB"
database_name = "zenshi"
database_id = "df04cb3e-eab2-4abd-9189-66ef1f28de78"
remote = true

[[r2_buckets]]
binding = "FAVICON_BUCKET"
bucket_name = "zenshi-favicons"

[triggers]
crons = ["0 2 * * *"]

[queues]
producers = [
  { queue = "gsc-sync", binding = "GSC_SYNC_QUEUE" }
]

consumers = [
  { queue = "gsc-sync", max_batch_size = 5, max_batch_timeout = 5, max_retries = 3, max_concurrency = 1 }
]

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1
